name: Print Interval
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run main.py
        run: python3 main.py